language: python

python:
  - "3.6"

env:
  - SECRET_KEY="TEST"
services:
  - postgresql
install:
  - pipenv install

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - python manage.py test