language: python

python:
  - "3.6"

env:
  global:
    - secure: "lgDblnFZVthsKjYsIIGNo+znZTisbSroGdt/oy8rBCABP11s0ZQpG+I10DQPM/b2/Fak8gOZu1k6zrWMPRYYJBXatsAJ1v18dbLhFZmiEH7lvwwbOg8W/1LIf5piRqoIHvUbtCDv/Abl3lIxa3b1yxnguns7kGnWFAnHzFJk1pdlR7TKG6R95NroxNC4SdnVabrtBpkeF8QunmQIslCBO6cRuRjcQIBUtMi6L3rYSwvwJOZesp7noudfb72u239GYi+S3MXccnqsl1e8RJVgl8yeYGDYvVxZINyaeMYIXHxiTHGMFHw1zCn1zfVPxATHRgupfh3YCAZxwHfx70NeU5wnK6HLSE5W96zUwCuQ+k0VaqnkOiX70Y4WVMu9uyl2aRKZZMfgcA26IAo28pTqaBGHg6XHZRHaVdrua4Ib7wwlAX7F+xI2CMU4cT+PlLBavfLui+D/xXl8YB5F159hlWsF9WpIQLoVT2fsnDEbg0uFn3xJwWpBKnJRv8nHHxWhy1HRfAH5Nm8qtAv31KVGH316h95Jr9tIeu/n5k/yS2Bb4Bge8G3xsCnbXSS22yepHcudFXRpsEKK5vfidmXti+IhWgzvVvdjRLFAQylXO6a8UCQiOr7BVIx2+cJxkDrbQvhW74aylbCh+b8q7WdO+QCKRM/+sfT0VMzSFBLJq2g="

services:
  - postgresql
install:
  - pipenv install

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - python manage.py test