# Generated by Django 3.0.7 on 2020-06-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='image',
            field=models.ImageField(null=True, upload_to='point'),
        ),
    ]
